import psycopg2

conn = psycopg2.connect('dbname=pitonDB user=postgres password=johanes')
cur = conn.cursor()

cur.execute('''
CREATE TABLE IF NOT EXISTS USER_LOGIN (USERID VARCHAR(10), USERNAME VARCHAR(50), PASSWORD VARCHAR(50), REGISTER_DATE DATE)
''')

cur.execute('''
CREATE TABLE IF NOT EXISTS CUSTOMERS (USERID VARCHAR(10), NAME VARCHAR(50), EMAIL VARCHAR(100), PHONE VARCHAR(20), ADDRESS VARCHAR(100), CITY VARCHAR(50), ZIPCODE VARCHAR(5))
''')

cur.execute('''
CREATE TABLE IF NOT EXISTS STOCK (ID_BARANG VARCHAR(4), DESCRIPTION VARCHAR(50), STOCK INTEGER)
''')

cur.execute('''
CREATE TABLE IF NOT EXISTS TRANSACTION (ID_TRANSACTION VARCHAR(15), ID_BARANG VARCHAR(4), USERID VARCHAR(10), QUANTITY INTEGER, TRANSACTION_DATE DATE)
''')

conn.commit()